.TH YOUTUBE\-SEARCH 1 youtube-search VERSION
.SH NAME
Youtube search \- A client to search for videos on youtube on the command line
.SH SYNOPSIS
.B youtube-search
.RB [
.IR OPTIONS
]
.RB [
.IR TEXT
SEARCH
]
.SH DESCRIPTION
.P
youtube-search is a command line client to search for videos on youtube and output the title and youtube link on standard out.
.SH OPTIONS
.TP
.B \-h, \-\-help
Prints help text for youtube-search.
.TP
.B \-f, \-\-format
Go template to format output. (default "{{ .Title }} - {{ .Href }}")

.SH EXIT STATUS
The following are all the status codes that the program will terminate with.
.TP
.B 0.
Program executed normally without any errors.
.TP
.B 1.
General execution error.
.TP
.B 127.
Could not reach youtube.
.SH USAGE
The youtube search client can be used to pipe result in to other programs. The following example searches youtube for the text "example" gets lets you select one result with the program dmenu and then opens the selected link in the web-browser surf.
.TR
.sp 2
.br
.ti +4
youtube-search example | dmenu -l 10 | awk '{ print $NF }' | xargs surf
.br
.sp
This can of couse be mixed and matched with any other utillity e.g. fzf, mpv, youtube-dl etc.
